DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS LISTAS_DE_TAREFAS;
DROP TABLE IF EXISTS TAREFAS;

CREATE TABLE USUARIOS (
    Id_Usuario INT PRIMARY KEY  AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(50) NOT NULL
);

CREATE TABLE LISTAS_DE_TAREFAS (
    Id_lista INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    Id_Usuario INT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id_Usuario)
);

CREATE TABLE TAREFAS (
    id_tarefa INT PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(255) NOT NULL,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_conclusao TIMESTAMP NULL,
    Id_lista INT NOT NULL,
    FOREIGN KEY (Id_lista) REFERENCES LISTAS_DE_TAREFAS(Id_lista)
);